[package]
name = "snake"
version = "0.1.1"
authors = ["Patryk Chodur <patrykchodur@icloud.com>"]
license = "MIT"
edition = "2021"
default-run = "snake"

[dependencies]
color-eyre = "0.6.2"
crossterm = "0.27.0"
eyre = "0.6.11"
log = "0.4.20"
log4rs = "1.2.0"
rand = "0.8.5"
ratatui = "0.24.0"
